//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Du.VS.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Du.VS.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助你开发SolidWorks 的本地化字符串。
        /// </summary>
        public static string AboutPage_Description {
            get {
                return ResourceManager.GetString("AboutPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要功能: 的本地化字符串。
        /// </summary>
        public static string AboutPage_MainFeature {
            get {
                return ResourceManager.GetString("AboutPage_MainFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.丰富的SolidWorks开发模板 的本地化字符串。
        /// </summary>
        public static string AboutPage_MF1 {
            get {
                return ResourceManager.GetString("AboutPage_MF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3.Visual Studio Signature 函数签名帮助信息 的本地化字符串。
        /// </summary>
        public static string AboutPage_MF3 {
            get {
                return ResourceManager.GetString("AboutPage_MF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.右击查看SolidWorks Api Help 的本地化字符串。
        /// </summary>
        public static string AboutPage_MF4 {
            get {
                return ResourceManager.GetString("AboutPage_MF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5.快速了解本机安装的SolidWorks和其插件 的本地化字符串。
        /// </summary>
        public static string AboutPage_MF5 {
            get {
                return ResourceManager.GetString("AboutPage_MF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6.SolidWorks 程序集引用管理器 的本地化字符串。
        /// </summary>
        public static string AboutPage_MF6 {
            get {
                return ResourceManager.GetString("AboutPage_MF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7.快速执行插件的卸载安装 的本地化字符串。
        /// </summary>
        public static string AboutPage_MF7 {
            get {
                return ResourceManager.GetString("AboutPage_MF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8.查看SolidWorks选择对象信息 的本地化字符串。
        /// </summary>
        public static string AboutPage_MF8 {
            get {
                return ResourceManager.GetString("AboutPage_MF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片来自 stocksnap.io 的本地化字符串。
        /// </summary>
        public static string AboutPage_PicFrom {
            get {
                return ResourceManager.GetString("AboutPage_PicFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三方库: 的本地化字符串。
        /// </summary>
        public static string AboutPage_ThirdParty {
            get {
                return ResourceManager.GetString("AboutPage_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.Visual Studio Quick Info 快速了解Api信息 的本地化字符串。
        /// </summary>
        public static string AddinPage_MF2 {
            get {
                return ResourceManager.GetString("AddinPage_MF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件管理器 的本地化字符串。
        /// </summary>
        public static string AddinView {
            get {
                return ResourceManager.GetString("AddinView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册一个SolidWorks dll插件 的本地化字符串。
        /// </summary>
        public static string AddinView_InstallTip {
            get {
                return ResourceManager.GetString("AddinView_InstallTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        public static string AddinView_Load {
            get {
                return ResourceManager.GetString("AddinView_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装的SolidWorks插件 的本地化字符串。
        /// </summary>
        public static string AddinView_SolidWorksAddinList {
            get {
                return ResourceManager.GetString("AddinView_SolidWorksAddinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本机SolidWorks列表 的本地化字符串。
        /// </summary>
        public static string AddinView_SolidWorksList {
            get {
                return ResourceManager.GetString("AddinView_SolidWorksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载当前选中的插件(执行前请关闭SolidWorks) 的本地化字符串。
        /// </summary>
        public static string AddinView_UnInstallTip {
            get {
                return ResourceManager.GetString("AddinView_UnInstallTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要获取此部分信息，请以管理员权限运行Visual Studio 的本地化字符串。
        /// </summary>
        public static string AdminRun {
            get {
                return ResourceManager.GetString("AdminRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集信息 的本地化字符串。
        /// </summary>
        public static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 嵌入到扩展的命名空间 的本地化字符串。
        /// </summary>
        public static string InteropDll {
            get {
                return ResourceManager.GetString("InteropDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ群 的本地化字符串。
        /// </summary>
        public static string QQGroup {
            get {
                return ResourceManager.GetString("QQGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制到项目路径 的本地化字符串。
        /// </summary>
        public static string RefManager_CopyDll {
            get {
                return ResourceManager.GetString("RefManager_CopyDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否选择 的本地化字符串。
        /// </summary>
        public static string RefManager_IsChoose {
            get {
                return ResourceManager.GetString("RefManager_IsChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否已经安装 的本地化字符串。
        /// </summary>
        public static string RefManager_IsInstall {
            get {
                return ResourceManager.GetString("RefManager_IsInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名 的本地化字符串。
        /// </summary>
        public static string RefManager_ProjectName {
            get {
                return ResourceManager.GetString("RefManager_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用源路径 的本地化字符串。
        /// </summary>
        public static string RefManager_SourceDll {
            get {
                return ResourceManager.GetString("RefManager_SourceDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SolidWork 程序集管理器 的本地化字符串。
        /// </summary>
        public static string RefManager_Title {
            get {
                return ResourceManager.GetString("RefManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本: 的本地化字符串。
        /// </summary>
        public static string RefManager_Version {
            get {
                return ResourceManager.GetString("RefManager_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前Dll版本 的本地化字符串。
        /// </summary>
        public static string RefManager_VersionTip {
            get {
                return ResourceManager.GetString("RefManager_VersionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中对象信息 的本地化字符串。
        /// </summary>
        public static string SelectionInfo_GetSelectionInfo {
            get {
                return ResourceManager.GetString("SelectionInfo_GetSelectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取选中对象 的本地化字符串。
        /// </summary>
        public static string SelectionInfo_GetSelectionObj {
            get {
                return ResourceManager.GetString("SelectionInfo_GetSelectionObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开SolidWork所在文件夹 的本地化字符串。
        /// </summary>
        public static string SWInfo_OpenSWFloder {
            get {
                return ResourceManager.GetString("SWInfo_OpenSWFloder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此电脑安装的SolidWorks 的本地化字符串。
        /// </summary>
        public static string SWInfo_PCSolidWorks {
            get {
                return ResourceManager.GetString("SWInfo_PCSolidWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前运行的SolidWorks 的本地化字符串。
        /// </summary>
        public static string SWInfo_RuningSW {
            get {
                return ResourceManager.GetString("SWInfo_RuningSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动选中的SolidWorks 的本地化字符串。
        /// </summary>
        public static string SWInfo_StartSW {
            get {
                return ResourceManager.GetString("SWInfo_StartSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸载 的本地化字符串。
        /// </summary>
        public static string UnInstall {
            get {
                return ResourceManager.GetString("UnInstall", resourceCulture);
            }
        }
    }
}
